name: shopping_app
description: A simple Flutter shopping app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  cupertino_icons: ^1.0.2
  cached_network_image: ^2.5.0

  flutter_staggered_grid_view: ^0.3.4
  flutter_swiper: ^1.1.6

  photo_view: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/icon2.png"
  adaptative_icon_background: "#ffffff"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf

        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
